apiVersion: ENC[AES256_GCM,data:+zQ=,iv:u9kAYNtFHLdQ2w1eC4pg3QgyBMKN/hC7oI3Vp4tt6FI=,tag:xkTKjUTM57daeTqISLJl5Q==,type:str]
kind: ENC[AES256_GCM,data:gH30Jrh7,iv:uYVOeQClF7qSup4MnL+lawumsMhthD+hb+cMRD1Zkrs=,tag:Xy64j3EIloGZBVFZHm6DQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jNozcteW85d9NJRCmu0=,iv:MHHFyWP6l51g2/mn7VxVlpBPvxmgSC3/M7l4E/SmMMA=,tag:CC+SNj7feOmifoVGTNZXAA==,type:str]
    namespace: ENC[AES256_GCM,data:LNQztDjetpGhEek=,iv:mis//jV+VtXivnf0EuylxlVqv2yuIvvI5LaRiaQCzXA=,tag:FyuWulw9Wsn16KgxkjLVYA==,type:str]
type: ENC[AES256_GCM,data:4c3Na4QPtT4VxllbdVvUhtF4gFwkzpn1NeXvr4is,iv:d1I8alubBYOyjDy3jUZIKczTCWYfjZJ+/nBAfHprS9Q=,tag:UXxYp82qA0eueHWPXHu+yA==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:J4hUphuTDqkNyUzqpsml4F65I6v9Vo8+RPyarn0g8KrHYu5lUlxUlQh+LwBST53JK5w6O41/ONmJdmFwQWXIHV92frd2PyGyIMQluTbdv8Z1ootgeMUi3LTVK2bpKExJhm79oQRZjbUoKbG+8OFPo+Cttyqz5HNs13Kt+yEvLGO/+imCo62lVKxKi058pR1uRqqmPrGz6zubgSeebO8ovCFhFFAQH68e8oYQeIioOPpNg3/kY4hFZYlGzPPQPvkt9SUGAhAiSjGdLI1a,iv:uRcVlb+9pPWHKC7Uvfzk0kQGU4VOJGC2sYExuXST8Vk=,tag:IlHh47fD96//Wau8d/BZjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQlNtMmFwc1FjWHkraUZI
            RWhyWk5xMU5udndDeHJzUXo1REoraTJMTVI4CjdUeEF5MnRPSHZ4OUhCU2RHTTBJ
            TUt1QWhpaUdVMlg1YlFkZ1FrWVh6N00KLS0tIE8xZmVUZW5CSzdaNEJPUzR3NVpF
            R2d2cUJrWkQ0UnZ0VXBEUEdUYzZVTjQKByCzRO2Y2Mx4SVozzI0M/n+aALlRkoG9
            bX+boAM7IIoHHgorMFKXhYuVIBkztzZECxoLloaWZ2mDmGxp2j8PGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T16:14:14Z"
    mac: ENC[AES256_GCM,data:B/zelByyFwkL/0A/mgFs1Sks2AdMIVO4Ks9U4Lljz6Xk3jkGZ19OGIFje3+Yr+YlomMQysfhvD7pwLZqgKWXfOu7e+6a4a2+jz0hz/gabdttgWXeKunjMTP1q3UoNtGkM0kumJeVQWCKFeqZT+Qy67Y8HYuy7V3Di8Wp649CtlQ=,iv:siLhWLrsEGPIU1BQe9/DbiR8Ro39Y1H9sJcSilRlnzw=,tag:9Cbo7LUxrvYT+Z0BtUwRyQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
