apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tdemo2dev
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: tdemo2dev
  namespace: dev
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: message
    value: tanzu2dev
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1
